services:
  odoo:
    image: "odoo:13.0"
    environment:
      - SERVICE_URL_ODOO_8069
      - HOST=postgresql
      - USER=$SERVICE_USER_POSTGRES
      - PASSWORD=$SERVICE_PASSWORD_POSTGRES
    ports:
      - "8069:8069"
    volumes:
      - "/home/odoo/alastor/config:/etc/odoo"
      - "odoo-web-data:/var/lib/odoo"
      - "/home/odoo/alastor/addons:/mnt/extra-addons"
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://127.0.0.1:8069"
      interval: 2s
      timeout: 10s
      retries: 30
  postgresql:
    image: "postgres:15-alpine"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - POSTGRES_DB=postgres
    healthcheck:
      test:
        - CMD-SHELL
        - "pg_isready -U $${POSTGRES_USER} -d postgres"
      interval: 5s
      timeout: 20s
      retries: 10
